import sqlite3
from db import db

class UserModel(db.Model):
    __tablename__ = 'users'
    #columns names
    id = db.Column(db.Integer, primary_key = True) #automately generated by sqlalchemy
    username = db.Column(db.String(80))
    password = db.Column(db.String(80))
    #auto pass the para into __init__()
    def __init__(self, username, password):
        self.username = username
        self.password = password
        
    def json (self):
        return {'username':self.username, 'password': self.password }
        
    def save_to_db(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def find_by_username(cls, username):
        return cls.query.filter_by(username = username).first() # return an UserModel object
        
    @classmethod
    def find_by_id(cls, _id):
        return cls.query.filter_by(id = _id).first()